/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Dataset */
        post: operations["import_dataset_api_v1_datasets_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_v1_datasets__dataset_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_api_v1_datasets__dataset_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/versions/{version}/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_v1_datasets__dataset_id__versions__version__cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matching/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v1_matching_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_v1_predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Predictions */
        post: operations["import_predictions_api_v1_predictions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_v1_predictions__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_dataset_api_v1_datasets_import_post */
        Body_import_dataset_api_v1_datasets_import_post: {
            /** Dataset Id */
            dataset_id?: string | null;
            /** Dataset Name */
            dataset_name?: string | null;
            /** File */
            file: string;
            /** Mapping */
            mapping?: string | null;
        };
        /** Body_import_predictions_api_v1_predictions_import_post */
        Body_import_predictions_api_v1_predictions_import_post: {
            /** Dataset Id */
            dataset_id?: string | null;
            /** Dataset Name */
            dataset_name?: string | null;
            /** Dataset Version */
            dataset_version?: number | null;
            /**
             * Evaluation Type
             * @enum {string}
             */
            evaluation_type: "answer" | "retrieval" | "both";
            /** File */
            file: string;
            /** Mapping */
            mapping?: string | null;
        };
        /** CandidateResponse */
        CandidateResponse: {
            /** Candidate */
            candidate: boolean;
            /** Predicted Index */
            predicted_index: number;
            /** Reason */
            reason: string;
            /** Reference Index */
            reference_index: number;
            /** Similarity */
            similarity: number | null;
        };
        /** CaseResponse */
        CaseResponse: {
            /** Case Id */
            case_id: string;
            /** Question */
            question: string;
            /** Reference Answer */
            reference_answer: string | null;
            /** Reference Chunks */
            reference_chunks: components["schemas"]["ReferenceChunkResponse"][] | null;
        };
        /** ChunkInput */
        ChunkInput: {
            /** Document Id */
            document_id: string;
            /** Text */
            text: string;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Latest Case Count */
            latest_case_count: number;
            /** Latest Version */
            latest_version: number;
            /** Name */
            name: string;
            /** Version Count */
            version_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Component
             * @enum {string}
             */
            component: "api" | "worker";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
        };
        /** ImportFailure */
        ImportFailure: {
            /** Error */
            error: string;
            /** Issues */
            issues: components["schemas"]["ImportIssueResponse"][];
        };
        /** ImportIssueResponse */
        ImportIssueResponse: {
            /** Code */
            code: string;
            /** Field */
            field: string | null;
            /** Line */
            line: number | null;
            /** Message */
            message: string;
        };
        /** PredictedChunkResponse */
        PredictedChunkResponse: {
            /** Chunk Id */
            chunk_id: string | null;
            /** Document Id */
            document_id: string;
            /** Source */
            source: string | null;
            /** Text */
            text: string;
        };
        /** PredictionBatchDetail */
        PredictionBatchDetail: {
            /** Created At */
            created_at: string;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Version */
            dataset_version: number;
            /**
             * Evaluation Type
             * @enum {string}
             */
            evaluation_type: "answer" | "retrieval" | "both";
            /** Id */
            id: string;
            /** Limit */
            limit: number;
            /** Matched Count */
            matched_count: number;
            /** Missing Case Count */
            missing_case_count: number;
            /** Offset */
            offset: number;
            /** Predictions */
            predictions: components["schemas"]["PredictionResponse"][];
            /** Record Count */
            record_count: number;
            /** Source Filename */
            source_filename: string;
        };
        /** PredictionBatchSummary */
        PredictionBatchSummary: {
            /** Created At */
            created_at: string;
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Version */
            dataset_version: number;
            /**
             * Evaluation Type
             * @enum {string}
             */
            evaluation_type: "answer" | "retrieval" | "both";
            /** Id */
            id: string;
            /** Matched Count */
            matched_count: number;
            /** Missing Case Count */
            missing_case_count: number;
            /** Record Count */
            record_count: number;
            /** Source Filename */
            source_filename: string;
        };
        /** PredictionResponse */
        PredictionResponse: {
            /** Answer */
            answer: string | null;
            /** Case Id */
            case_id: string;
            /** Contexts */
            contexts: components["schemas"]["PredictedChunkResponse"][] | null;
            /** Latency Ms */
            latency_ms: number | null;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /**
             * Model Name
             * @default BAAI/bge-small-zh-v1.5
             */
            model_name: string;
            /** Model Path */
            model_path?: string | null;
            /**
             * Offline
             * @default false
             */
            offline: boolean;
            /** Predicted Chunks */
            predicted_chunks: components["schemas"]["ChunkInput"][];
            /** Reference Chunks */
            reference_chunks: components["schemas"]["ChunkInput"][];
            /**
             * Threshold
             * @default 0.8
             */
            threshold: number;
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Model Id */
            model_id: string;
            /** Pairs */
            pairs: components["schemas"]["CandidateResponse"][];
            /** Threshold */
            threshold: number;
        };
        /** ReferenceChunkResponse */
        ReferenceChunkResponse: {
            /** Document Id */
            document_id: string;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionDetail */
        VersionDetail: {
            /** Case Count */
            case_count: number;
            /** Cases */
            cases: components["schemas"]["CaseResponse"][];
            /** Created At */
            created_at: string;
            /** Dataset Id */
            dataset_id: string;
            /** Id */
            id: string;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Source Filename */
            source_filename: string;
            /** Total */
            total: number;
            /** Version */
            version: number;
        };
        /** VersionSummary */
        VersionSummary: {
            /** Case Count */
            case_count: number;
            /** Created At */
            created_at: string;
            /** Dataset Id */
            dataset_id: string;
            /** Id */
            id: string;
            /** Source Filename */
            source_filename: string;
            /** Version */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
        };
    };
    import_dataset_api_v1_datasets_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_dataset_api_v1_datasets_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionSummary"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportFailure"];
                };
            };
        };
    };
    list_versions_api_v1_datasets__dataset_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_datasets__dataset_id__versions__version__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_v1_datasets__dataset_id__versions__version__cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                version: number;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    preview_api_v1_matching_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionBatchSummary"][];
                };
            };
        };
    };
    import_predictions_api_v1_predictions_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_predictions_api_v1_predictions_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionBatchSummary"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportFailure"];
                };
            };
        };
    };
    get_batch_api_v1_predictions__batch_id__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
