import { expect, test } from '@playwright/test'

test('core forms and upload dialog remain operable across workspaces', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /上传原文/ }).click()
  const dialog = page.getByRole('dialog', { name: /上传原文/ })
  await expect(dialog.getByLabel('Collection Name（集合名称）')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Upload（上传）' })).toBeVisible()
  const bounds = await dialog.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(900)
  await dialog.getByRole('button', { name: /关闭/ }).click()
  await expect(dialog).toBeHidden()

  const nav = page.getByRole('navigation', { name: /主导航/ })
  await nav.getByRole('button', { name: /候选生成/ }).click()
  await expect(page.getByLabel('Target Case Count（目标条数）')).toBeVisible()
  await nav.getByRole('button', { name: /HTTP 目标/ }).click()
  await expect(page.getByLabel('Endpoint URL（接口 URL）')).toBeVisible()
  await nav.getByRole('button', { name: /评价场景/ }).click()
  await expect(page.getByLabel('Faithfulness（忠实度） · Evaluation Criteria（评价标准）')).toBeVisible()
  await nav.getByRole('button', { name: /评测运行/ }).click()
  await expect(page.getByLabel('Evaluation Mode（评测模式）')).toBeVisible()
  await nav.getByRole('button', { name: /系统状态/ }).click()
  await expect(page.getByText(/管理 API/)).toBeVisible()
  await expect(page.getByText(/任务 Worker/)).toBeVisible()
})

test('upload dialog remains above compact navigation', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 })
  await page.goto('/')
  await page.getByRole('button', { name: /上传原文/ }).click()
  const dialog = page.getByRole('dialog', { name: /上传原文/ })
  await expect(dialog.getByLabel('Collection Name（集合名称）')).toBeVisible()
  await dialog.getByRole('button', { name: /关闭/ }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('button', { name: /打开导航/ })).toBeVisible()
})
