import { expect, test } from '@playwright/test'

test('core forms and upload dialog remain operable across workspaces', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /上传原文/ }).click()
  const dialog = page.getByRole('dialog', { name: /上传原文/ })
  await expect(dialog.getByLabel('Collection Name（集合名称）')).toBeVisible()
  await expect(dialog.getByLabel('Chunk Size (characters)（切块大小，字符）')).toHaveValue('1000')
  await expect(dialog.getByLabel('Chunk Overlap (characters)（重叠量，字符）')).toHaveValue('100')
  await expect(dialog.getByRole('button', { name: 'Upload（上传）' })).toBeVisible()
  const bounds = await dialog.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(900)
  await dialog.getByRole('button', { name: /关闭/ }).click()
  await expect(dialog).toBeHidden()

  const nav = page.getByRole('navigation', { name: /主导航/ })
  await nav.getByRole('button', { name: /候选生成/ }).click()
  await expect(page.getByLabel('Target Case Count（目标条数）')).toBeVisible()
  await expect(page.getByText('Multi-Chunk Ratio（多切块比例） · 30%（百分比）')).toBeVisible()
  await nav.getByRole('button', { name: /HTTP 目标/ }).click()
  await expect(page.getByLabel('Endpoint URL（接口 URL）')).toBeVisible()
  await expect(page.getByLabel('Timeout (seconds)（超时，秒）')).toHaveValue('30')
  await nav.getByRole('button', { name: /评价场景/ }).click()
  await expect(page.getByLabel('Faithfulness（忠实度） · Evaluation Criteria（评价标准）')).toBeVisible()
  await nav.getByRole('button', { name: /评测运行/ }).click()
  await expect(page.getByLabel('Evaluation Mode（评测模式）')).toBeVisible()
  await expect(page.getByLabel('Similarity Threshold (-1 to 1, unitless)（相似度阈值，-1 至 1，无单位）')).toHaveValue('0.8')
  await nav.getByRole('button', { name: /系统状态/ }).click()
  await expect(page.getByText(/管理 API/)).toBeVisible()
  await expect(page.getByText(/任务 Worker/)).toBeVisible()
})

test('upload dialog remains above compact navigation', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 })
  await page.goto('/')
  await page.getByRole('button', { name: /上传原文/ }).click()
  const dialog = page.getByRole('dialog', { name: /上传原文/ })
  await expect(dialog.getByLabel('Collection Name（集合名称）')).toBeVisible()
  await dialog.locator('input[type=file]').setInputFiles({ name: 'sample.txt', mimeType: 'text/plain', buffer: Buffer.from('abc') })
  await expect(dialog.getByText('sample.txt · 3 bytes（字节） · Document ID（文档 ID）')).toBeVisible()
  await expect(dialog.getByText('Chunk Size (characters)（切块大小，字符）')).toBeVisible()
  await expect(dialog.getByText('Chunk Overlap (characters)（重叠量，字符）')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await dialog.getByRole('button', { name: /关闭/ }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('button', { name: /打开导航/ })).toBeVisible()
})
